name: my-ddo
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - spacy
  - geopy
  - unidecode
  - geonamescache
  - jupyter
  - ipykernel 